name: "safe_step"
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  rename_app: ^1.6.2
  flutter_blue_plus: ^1.35.3
  permission_handler: ^12.0.0+1
  flutter_tts: ^4.2.2
  provider: ^6.1.4
  latlong2: ^0.9.1
  open_route_service: ^1.2.7
  flutter_map: ^8.1.1
  geolocator: ^14.0.0
  http: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
